CSS-918 TF Refactor
cloudstoragesec/terraform-aws-cloud-storage-security pull request #1
Opened 2024-02-16 21:13 UTC by sh-dan

CSS as a module!

2024-03-05 16:44 UTC, waldowernli approved these changes

2024-03-06 15:22 UTC, david-dreyer approved these changes
Only thing I have to note is that we are losing lots of documentation detail that is in README.md and DEPLOYMENT.md in the other repo.

Is it expected that those will go into our helpdocs instead?

2024-03-06 17:58 UTC, sh-dan commented
> Only thing I have to note is that we are losing lots of documentation detail that is in README.md and DEPLOYMENT.md in the other repo.
> 
> Is it expected that those will go into our helpdocs instead?

For README: 
The inputs, outputs and how many resources should be auto generated by the registry so I didn't move those over. 
We can dupe them in the readme if we want to. Here's an example of a module with a lot of inputs/outputs and a copy in readme: https://registry.terraform.io/modules/terraform-aws-modules/dynamodb-table/aws/latest

As far as file descriptions -- those are going to be hidden away from the users and they shouldn't be changing those. 

DEPLOYMENT:
I copied over the Prerequisite for subscription as that's the most important part. 
The rest is a few dupes as far as inputs and how to use TF with Terraform Cloud. 
If users are looking at the registry they are expected to know how to use TF in the first place as far as creds and basics go. 
We can move some of this info into help docs and point them to Terraform documentation, but don't think it belongs in this repo. Same goes for Terraform Cloud instructions.

2024-03-11 20:55 UTC, yeapiekiyay requested changes
Just a quick fix for govcloud deployments.  Other than that, a couple nitpicks around moving common things to locals which aren't necessary, but clean things up a bit. Great job!

2024-03-11 20:55 UTC, yeapiekiyay commented on locals.tf
> +  ecr_account              = coalesce(var.ecr_account, "${local.aws_region}" == "us-gov-west-1" ? "822167061992" : "564477214187")
I think we need to check AWS partition for the Gov partition instead here, since they could deploy in `us-gov-east-1` as well.

2024-03-11 20:55 UTC, yeapiekiyay commented on main.tf
> +}
Maybe this belongs in `ecs_service.tf` instead?

2024-03-11 20:55 UTC, yeapiekiyay commented on ssm.tf
> +  name  = "/${var.parameter_prefix}-${local.application_id}/Config/DynamoTableNamePrefix"
Consider making the prefix (`/${var.parameter_prefix}-${local.application_id}/Config`) a local.

2024-03-11 20:55 UTC, yeapiekiyay commented on variables.tf
> +  description = "The CIDR block which is allowed access to the CSS Console (e.g. 0.0.0.0/24 for open access)"
Update to:

> 0.0.0.0/0 for open access

2024-03-11 20:57 UTC, yeapiekiyay commented
> > Only thing I have to note is that we are losing lots of documentation detail that is in README.md and DEPLOYMENT.md in the other repo.
> > Is it expected that those will go into our helpdocs instead?
> 
> For README: The inputs, outputs and how many resources should be auto generated by the registry so I didn't move those over. We can dupe them in the readme if we want to. Here's an example of a module with a lot of inputs/outputs and a copy in readme: https://registry.terraform.io/modules/terraform-aws-modules/dynamodb-table/aws/latest
> 
> As far as file descriptions -- those are going to be hidden away from the users and they shouldn't be changing those.
> 
> DEPLOYMENT: I copied over the Prerequisite for subscription as that's the most important part. The rest is a few dupes as far as inputs and how to use TF with Terraform Cloud. If users are looking at the registry they are expected to know how to use TF in the first place as far as creds and basics go. We can move some of this info into help docs and point them to Terraform documentation, but don't think it belongs in this repo. Same goes for Terraform Cloud instructions.

To elaborate on Dan's response, the [TF Standard Module structure](https://developer.hashicorp.com/terraform/language/modules/develop/structure) notes the following:
> The README doesn't need to document inputs or outputs of the module because tooling will automatically generate this. If you are linking to a file or embedding an image contained in the repository itself, use a commit-specific absolute URL so the link won't point to the wrong version of a resource in the future.

2024-03-11 21:41 UTC, yeapiekiyay approved these changes

2024-03-11 21:42 UTC, merged